name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
      - dev
      - stage
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Realiza login no Docker Hub
      with:
        username: ${{ secrets.USER }} 
        password: ${{ secrets.PASSWD }}  

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.USER }}/devops-backend:$GITHUB_SHA .  # Build da imagem
        docker tag ${{ secrets.USER }}/devops-backend:$GITHUB_SHA ${{ secrets.USER }}/devops-backend:latest  # Marca a imagem como "latest"

    - name: Push Docker image
      run: |
        docker push ${{ secrets.USER }}/devops-backend:$GITHUB_SHA  # Faz o push da imagem com o sha do commit
        docker push ${{ secrets.USER }}/devops-backend:latest  # Push da imagem com a tag "latest"
