name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
      - dev
      - stage
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Extract Medatada
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
       images: reginaabarbara/devops-backend

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Realiza login no Docker Hub
      with:
        username: ${{ secrets.USER }} 
        password: ${{ secrets.PASSWD }}  

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.USER }}/devops-backend:$GITHUB_SHA . 
        docker tag ${{ secrets.PASSWD }}/devops-backend:$GITHUB_SHA ${{ secrets.USER }}/devops-backend:${{ steps.meta.outputs.tags }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.USER }}/devops-backend:$GITHUB_SHA 
        docker push ${{ secrets.PASSWD }}/devops-backend:${{ steps.meta.outputs.tags }}
            
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{  steps.meta.outputs.labels  }}
