name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
      - dev
      - stage
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Extract Medatada
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
       images: reginaabarbara/devops-backend    


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.USER }} 
        password: ${{ secrets.PASSWD }}  

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        build-args: |
          mode=${{ github.ref_name }}
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{  steps.meta.outputs.labels  }}
